const Homeproduct = [
  {
    id: 1,
    Title: "Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB",
    Cat: "Tablet",
    Price: "723",
    Img: "Ecommerce-Website/products/p0.jpg",
  },
  {
    id: 2,
    Title: "Tune 710BT Wireless",
    Cat: "Headphone",
    Price: "72",
    Img: "Ecommerce-Website/products/p1.jpg",
  },
  {
    id: 3,
    Title: "HUAWEI Band 8",
    Cat: "Smart Watch",
    Price: "168",
    Img: "Ecommerce-Website/products/p2.jpg",
  },
  {
    id: 4,
    Title: "EOS M50 Mark II ",
    Cat: "Camera",
    Price: "1049",
    Img: "Ecommerce-Website/products/p3.jpg",
  },
  {
    id: 5,
    Title: "JOYROOM 10000 mAh 22.5W LED Display Battery Status",
    Cat: "Powerbank",
    Price: "49",
    Img: "Ecommerce-Website/products/p4.jpg",
  },
  {
    id: 6,
    Title: "Xigmatek Xigmatek Liquid Killer X 240",
    Cat: "Heat pipe",
    Price: "156",
    Img: "Ecommerce-Website/products/p5.jpg",
  },
  {
    id: 7,
    Title: "PlayStation 5",
    Cat: "Gaming",
    Price: "2089",
    Img: "Ecommerce-Website/products/p6.jpg",
  },
  {
    id: 8,
    Title: "Redmi Power Bank 10000mAh Black",
    Cat: "Powerbank",
    Price: "386",
    Img: "Ecommerce-Website/products/p7.jpg",
  },
  {
    id: 9,
    Title: "Redmi Power Bank 10000mAh Black",
    Cat: "Powerbank",
    Price: "386",
    Img: "Ecommerce-Website/products/p7.jpg",
  },
  {
    id: 10,
    Title: "PlayStation 5",
    Cat: "Gaming",
    Price: "2089",
    Img: "Ecommerce-Website/products/p6.jpg",
  },
  {
    id: 11,
    Title: "EOS M50 Mark II ",
    Cat: "Camera",
    Price: "1049",
    Img: "Ecommerce-Website/products/p3.jpg",
  },
  {
    id: 12,
    Title: "Galaxy Tab S6 Lite 10.4 inch Android Tablet 128GB",
    Cat: "Tablet",
    Price: "723",
    Img: "Ecommerce-Website/products/p0.jpg",
  },
];

export default Homeproduct;
